apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay staging — estende la base.
# Personalizzazioni future: image tag versionato, repliche, TLS, ConfigMap staging.
namespace: construct

resources:
  - ../../base/web
