apiVersion: v1
kind: ConfigMap
metadata:
  name: web-construct-config
  namespace: construct
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  MAIL_PROVIDER: "resend"
  AUTH_URL: "http://construct.local"
  RESEND_FROM: "noreply@frontiere.io"
