apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: construct

resources:
  - ../../base/web
  - ingress.yaml

images:
  - name: web-construct
    newName: web-construct
    newTag: local
